
// This file is not to be modified.
// It is automatically generated by the Firebase Studio.
// If you need to change your Firebase config, please do so from the Studio UI.
import { FirebaseOptions } from 'firebase/app';

// This is the client-side config object for your Firebase project.
// It's pulled from the Firebase App settings in the Firebase console.
export const firebaseConfig: FirebaseOptions = {
    "apiKey": "test",
    "authDomain": "test",
    "projectId": "studio-6692487483-8434a",
    "storageBucket": "test",
    "messagingSenderId": "test",
    "appId": "test",
    "measurementId": "test"
};
