'use server';

// NOTE: This is a mock implementation.
// In a real application, you would use a Genkit flow with an AI model
// to generate the website content based on the prompt.

interface WebFile {
    name: string;
    language: string;
    content: string;
}

export async function handleWebsiteGeneration(prompt: string): Promise<WebFile[]> {
  console.log(`Generating website for prompt: ${prompt}`);

  // Simulate AI processing time
  await new Promise(resolve => setTimeout(resolve, 1500));

  // Return mock data based on a simple prompt keyword
  if (prompt.toLowerCase().includes('portfolio')) {
    return [
      {
        name: 'index.html',
        language: 'html',
        content: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Photographer Portfolio</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>John Doe | Photographer</h1>
    </header>
    <main>
        <div class="gallery">
            <img src="https://picsum.photos/seed/1/600/400" alt="Landscape Photo 1">
            <img src="https://picsum.photos/seed/2/600/400" alt="Landscape Photo 2">
            <img src="https://picsum.photos/seed/3/600/400" alt="Landscape Photo 3">
        </div>
    </main>
</body>
</html>`
      },
      {
        name: 'style.css',
        language: 'css',
        content: `body { 
    font-family: sans-serif; 
    margin: 0; 
    background-color: #111; 
    color: #eee;
}
header { text-align: center; padding: 2rem 0; }
.gallery { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1rem; padding: 1rem; }
img { width: 100%; height: auto; border-radius: 8px; }`
      },
      {
        name: 'script.js',
        language: 'javascript',
        content: `console.log("Portfolio page loaded!");`
      }
    ];
  }

  // Default simple site
  return [
    {
      name: 'index.html',
      language: 'html',
      content: `<!DOCTYPE html>
<html>
<head>
  <title>AI Generated Site</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <h1>${prompt}</h1>
  <p>This website was generated by an AI based on your prompt.</p>
  <script src="script.js"></script>
</body>
</html>`
    },
    {
      name: 'style.css',
      language: 'css',
      content: `body { font-family: sans-serif; background-color: #282c34; color: white; text-align: center; padding-top: 5rem; }`
    },
    {
      name: 'script.js',
      language: 'javascript',
      content: `console.log("AI site loaded!");`
    }
  ];
}

export async function handleAiChat(text: string, image?: string): Promise<string> {
    console.log(`AI Chat received: ${text}`, { hasImage: !!image });

    // Simulate AI processing time
    await new Promise(resolve => setTimeout(resolve, 1200));

    let response = `This is a simulated AI response to your message: "${text}".`;
    if(image) {
        response += " I have also "received" the image you uploaded."
    }

    if(text.toLowerCase().includes("change background")) {
        response += " To change the background color, you can modify the 'background-color' property in your CSS file."
    }

    return response;
}
