
'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowRight, Eye, Wand2, Sparkles, LayoutTemplate, Code, Bot } from 'lucide-react';
import { useAuth } from '@/context/auth-context';
import TypewriterEffect from '@/components/typewriter-effect';
import { cn } from '@/lib/utils';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import Image from 'next/image';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"


const animatedTitles = [
    "Build a website with a single prompt.",
    "Your vision, brought to life by AI.",
    "From idea to website in seconds.",
    "AI-powered website generation.",
    "Create, customize, and deploy with ease.",
    "The future of web design is here."
];

const features = [
    {
        icon: <Wand2 className="w-8 h-8 text-primary" />,
        title: "AI-Powered Generation",
        description: "Describe your ideal website, and our AI will generate the initial design and code, giving you a running start.",
    },
    {
        icon: <Code className="w-8 h-8 text-primary" />,
        title: "View the Code",
        description: "Instantly see the HTML, CSS, and JavaScript generated by the AI. Learn from it or copy it for your own projects.",
    },
     {
        icon: <Eye className="w-8 h-8 text-primary" />,
        title: "Live Preview",
        description: "Instantly see your changes reflected in a live preview. Iterate quickly and design with confidence.",
    },
    {
        icon: <Sparkles className="w-8 h-8 text-primary" />,
        title: "Free to Start",
        description: "Experiment and build your first website for free on our trial page. Sign up to save your work.",
    },
];

const AiIcon = () => (
    <Bot className="w-8 h-8 text-primary" />
);


export default function Home() {
  const { user } = useAuth();
  
  return (
    <div
      className={cn(
        "flex flex-col min-h-screen w-full bg-background text-foreground"
      )}
    >
      <main className="flex-1">
        <section className="relative container mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24 overflow-hidden">
            <div className="absolute inset-0 -z-20 animated-gradient-background opacity-20 dark:opacity-30"></div>
            <div className="absolute inset-0 -z-10 bg-gradient-to-t from-background via-transparent to-background"></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
                <div className="flex flex-col items-start text-left z-10 animate-fade-in-up" style={{ animationDelay: '0.2s' }}>
                    <TypewriterEffect
                        texts={animatedTitles}
                        className="text-4xl sm:text-5xl lg:text-6xl font-bold font-display tracking-tight mb-4 min-h-[120px] sm:min-h-[140px] lg:min-h-[150px]"
                    />
                    <p className={cn("text-base sm:text-lg lg:text-xl max-w-xl mb-8 text-muted-foreground")}>
                        Byte AI is a powerful, AI-powered website builder.
                        Describe your vision, and watch as our AI brings it to life in seconds.
                        The future of creation is here.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4">
                        <Link href="/create">
                        <Button size="lg" className="font-bold text-lg w-full sm:w-auto">
                            Start Creating <ArrowRight className="ml-2 h-5 w-5" />
                        </Button>
                        </Link>
                        {!user && (
                        <Link href="/try">
                            <Button size="lg" variant="outline" className={cn("font-bold text-lg w-full sm:w-auto")}>
                            Try for Free
                            </Button>
                        </Link>
                        )}
                    </div>
                </div>

                <div className="z-10 block animate-fade-in-up" style={{ animationDelay: '0.4s' }}>
                  <Card className="transform-gpu transition-transform duration-500 hover:rotate-[-2deg] hover:shadow-2xl bg-card/50 backdrop-blur-sm">
                      <CardContent className="p-2">
                          <div className="bg-muted/30 p-4 rounded-lg">
                              <div className="bg-background/80 rounded-md shadow-inner-lg overflow-hidden border">
                                  <div className="h-8 flex items-center justify-between px-3 bg-muted/50 border-b">
                                      <div className="flex items-center gap-1.5">
                                          <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
                                          <div className="w-3 h-3 rounded-full bg-yellow-500/80"></div>
                                          <div className="w-3 h-3 rounded-full bg-green-500/80"></div>
                                      </div>
                                      <div className="text-sm text-muted-foreground font-mono bg-background px-4 py-0.5 rounded-md border">
                                        index.html
                                      </div>
                                  </div>
                                  <div className="p-6 text-left space-y-2 font-mono text-xs text-muted-foreground">
                                      <p>&lt;<span className="text-blue-400">div</span> <span className="text-green-400">class</span>=<span className="text-yellow-400">"hero"</span>&gt;</p>
                                      <p className="pl-4">&lt;<span className="text-blue-400">h1</span>&gt;My Awesome Website&lt;/<span className="text-blue-400">h1</span>&gt;</p>
                                      <p className="pl-4">&lt;<span className="text-blue-400">p</span>&gt;Generated by AI...&lt;/<span className="text-blue-400">p</span>&gt;</p>
                                      <div className="w-full h-4 bg-muted rounded-full animate-pulse my-2"></div>
                                      <div className="w-3/4 h-4 bg-muted rounded-full animate-pulse"></div>
                                      <p>&lt;/<span className="text-blue-400">div</span>&gt;</p>
                                  </div>
                              </div>
                          </div>
                      </CardContent>
                  </Card>
                </div>
            </div>
        </section>

        <section className="py-16 md:py-24 bg-muted/50">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center mb-12 animate-fade-in-up">
                    <h2 className="text-3xl sm:text-4xl font-bold font-display">A New Way to Build Websites</h2>
                    <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
                        We combine a powerful AI model with an intuitive interface to make web development accessible to everyone.
                    </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                     <Accordion type="single" collapsible className="w-full space-y-4">
                        {features.slice(0, 2).map((feature, index) => (
                            <AccordionItem value={`item-${index}`} key={index} className="bg-card border-none rounded-lg shadow-sm animate-fade-in-up" style={{ animationDelay: `${index * 0.1 + 0.3}s` }}>
                                <AccordionTrigger className="p-6 text-left hover:no-underline hover:shadow-md hover:shadow-primary/20 data-[state=open]:shadow-md data-[state=open]:shadow-primary/20 transition-shadow rounded-lg">
                                    <div className="flex items-start gap-4">
                                        {feature.icon}
                                        <div>
                                            <h3 className="text-xl font-semibold">{feature.title}</h3>
                                        </div>
                                    </div>
                                </AccordionTrigger>
                                <AccordionContent className="p-6 pt-0">
                                    <p className="text-muted-foreground ml-12">{feature.description}</p>
                                </AccordionContent>
                            </AccordionItem>
                        ))}
                    </Accordion>
                     <Accordion type="single" collapsible className="w-full space-y-4">
                        {features.slice(2).map((feature, index) => (
                           <AccordionItem value={`item-${index + 2}`} key={index+2} className="bg-card border-none rounded-lg shadow-sm animate-fade-in-up" style={{ animationDelay: `${(index+2) * 0.1 + 0.3}s` }}>
                                <AccordionTrigger className="p-6 text-left hover:no-underline hover:shadow-md hover:shadow-primary/20 data-[state=open]:shadow-md data-[state=open]:shadow-primary/20 transition-shadow rounded-lg">
                                    <div className="flex items-start gap-4">
                                        {feature.icon}
                                        <div>
                                            <h3 className="text-xl font-semibold">{feature.title}</h3>
                                        </div>
                                    </div>
                                </AccordionTrigger>
                                <AccordionContent className="p-6 pt-0">
                                    <p className="text-muted-foreground ml-12">{feature.description}</p>
                                </AccordionContent>
                            </AccordionItem>
                        ))}
                    </Accordion>
                </div>
            </div>
        </section>

        <section className="py-16 md:py-24 bg-background">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center mb-12 animate-fade-in-up">
                    <Badge variant="outline" className="text-sm">Powered by Google AI</Badge>
                    <h2 className="text-3xl sm:text-4xl font-bold font-display mt-4">Pioneering the Future of Web Design</h2>
                    <p className="mt-4 text-lg text-muted-foreground max-w-3xl mx-auto">
                        Byte AI leverages state-of-the-art generative artificial intelligence to turn your ideas into reality. Our partnership with Google AI allows us to provide a robust, scalable, and powerful platform for instant website creation.
                    </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center max-w-5xl mx-auto">
                    <Card className="bg-card/50 animate-fade-in-up" style={{ animationDelay: '0.3s' }}>
                        <CardHeader>
                            <div className="flex items-center gap-2 mb-2">
                                <Sparkles className="w-8 h-8 text-primary" />
                                <h3 className="text-2xl font-display">About Byte AI</h3>
                            </div>
                        </CardHeader>
                        <CardContent>
                            <p className="text-muted-foreground">
                                Byte AI is more than just a tool; it's your creative partner. Our mission is to democratize web design, making it accessible for everyone—from solo entrepreneurs to established businesses—to bring their digital visions to life without writing a single line of code. We believe in the power of ideas, and our platform is built to get you from concept to a live website in minutes.
                            </p>
                        </CardContent>
                    </Card>
                    <Card className="bg-card/50 animate-fade-in-up" style={{ animationDelay: '0.5s' }}>
                        <CardHeader>
                            <div className="flex items-center gap-2 mb-2">
                                <AiIcon />
                                <h3 className="text-2xl font-display">Partnership with Google AI</h3>
                            </div>
                        </CardHeader>
                        <CardContent>
                            <p className="text-muted-foreground">
                                By harnessing the power of Google's advanced generative models, we can interpret complex creative prompts and translate them into beautiful, functional, and responsive websites. This collaboration ensures that our users benefit from cutting-edge AI technology, resulting in higher quality designs, more reliable code generation, and a seamless creative process.
                            </p>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </section>
      </main>

      <footer className={cn("py-6 text-center text-sm z-10 text-muted-foreground bg-background")}>
        <p>
          © 2025 Enzo Gimena's Ai, All rights reserved.
        </p>
      </footer>
    </div>
  );
}

    
